name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v2
  
    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: compiler:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run tests
      run: docker run --name compiler -i --rm compiler bash -c "cargo build && cargo test && ./target/debug/compiler e2e"
